### ISSUE TITLE
安卓客户端搜索时显示加载失败

### ISSUE THREAD

**Issue by wangkai6688** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#103]
安卓客户端搜索时显示 加载失败，请点击重试，同时弹出 网络异常，请检查的弹窗 ，在手机上安装ca证书也无效
清空数据后可以正常使用，但是使用流量搜索一次后再连回来就又不行了，每次都清除数据也不是办法😅

**Comment by zlf179** [comment]
对 日志显示这个错误
internal/fs/utils.js:332
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/usr/share/unblockneteasemusic/server.key'
    at Object.openSync (fs.js:497:3)
    at Object.readFileSync (fs.js:393:35)
    at Object.9550 (/usr/share/unblockneteasemusic/core/app.js:14026:13)
    at __webpack_require__ (/usr/share/unblockneteasemusic/core/app.js:16004:41)
    at /usr/share/unblockneteasemusic/core/app.js:16128:16
    at /usr/share/unblockneteasemusic/core/app.js:16203:3
    at Object.<anonymous> (/usr/share/unblockneteasemusic/core/app.js:16205:12)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/usr/share/unblockneteasemusic/server.key'
}
