### ISSUE TITLE
帮忙看下为什么windows客户端提示网络无法连接

### ISSUE THREAD

**Issue by suyu0925** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#173]
```
Launching luci-app-unblockneteasmusic Debugging Tool...


OpenWrt info:
{
	"kernel": "5.4.188",
	"hostname": "OpenWrt",
	"system": "Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz",
	"model": "innotek GmbH VirtualBox",
	"board_name": "innotek-gmbh-virtualbox",
	"release": {
		"distribution": "OpenWrt",
		"version": "21.02.3",
		"revision": "r16554-1d4dea6d4f",
		"target": "x86/64",
		"description": "OpenWrt 21.02.3 r16554-1d4dea6d4f"
	}
}


uclient-fetch info:
Package: uclient-fetch
Version: 2021-05-14-6a6011df-1
Depends: libc, libuclient20201210
Provides: wget
Status: install user installed
Section: net
Architecture: x86_64
Size: 7950
Filename: uclient-fetch_2021-05-14-6a6011df-1_x86_64.ipk
Description: Tiny wget replacement using libuclient
Installed-Time: 1650113974

Package: libustream-wolfssl20201210
Version: 2022-01-16-868fd881-1
Depends: libc, libubox20210516, libwolfssl5.2.0.99a5b54a
Provides: libustream-wolfssl
Conflicts: libustream-openssl
Status: install user installed
Section: libs
Architecture: x86_64
Size: 5023
Filename: libustream-wolfssl20201210_2022-01-16-868fd881-1_x86_64.ipk
Description: ustream SSL Library (wolfssl)
Installed-Time: 1650113974

Package: libustream-openssl20201210
Version: 2022-01-16-868fd881-1
Depends: libc, libubox20210516, libopenssl1.1
Provides: libustream-openssl
Status: unknown ok not-installed
Section: libs
Architecture: x86_64
Size: 5418
Filename: libustream-openssl20201210_2022-01-16-868fd881-1_x86_64.ipk
Description: ustream SSL Library (openssl)

Package: libustream-mbedtls20201210
Version: 2022-01-16-868fd881-1
Depends: libc, libubox20210516, libmbedtls12
Provides: libustream-mbedtls
Conflicts: libustream-openssl, libustream-wolfssl
Status: unknown ok not-installed
Section: libs
Architecture: x86_64
Size: 5238
Filename: libustream-mbedtls20201210_2022-01-16-868fd881-1_x86_64.ipk
Description: ustream SSL Library (mbedtls)

Downloading 'https://api.github.com/repos/UnblockNeteaseMusic/server/commits?sha=enhanced&path=precompiled'
Connecting to 18.179.245.253:443
Writing to stdout

Download completed (125303 bytes)
7cbc0acff167f78748f69709894dd6a0747ccdbc


Node.js info:
Package: node
Version: v14.20.0-1
Depends: libc, libstdcpp6, libopenssl1.1, zlib, libnghttp2-14, libuv1, libcares, libatomic1
Status: install ok installed
Section: lang
Architecture: x86_64
Size: 10673103
Filename: node_v14.20.0-1_x86_64.ipk
Description: Node.jsÂ® is a JavaScript runtime built on Chrome's V8 JavaScript engine. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient. Node.js' package ecosystem, npm, is the largest ecosystem of open source libraries in the world. *** The following preparations must be made on the host side. *** 1. gcc 6.3 or higher is required. 2. To build a 32-bit target, gcc-multilib, g++-multilib are required. 3. Requires libatomic package. (If necessary, install the 32-bit library at the same time.) ex) sudo apt-get install gcc-multilib g++-multilib
Installed-Time: 1658717797

Node.js is placed at /usr/bin/node
Node.js version: v14.20.0


luci-app-unblockneteasmusic info:
Package: luci-app-unblockneteasemusic
Version: 2.13-1
Depends: libc, busybox, dnsmasq-full, ipset, jsonfilter, node, uclient-fetch
Status: install user installed
Architecture: all
Conffiles:
 /etc/config/unblockneteasemusic e9413f9ce065cfb7b875d1948c6d3258772ab8854b7ccf193df49c3c8b6cca20
Installed-Time: 1658717798

-rw-r--r--    1 root     root         282 Jul 26 06:29 /etc/config/unblockneteasemusic
-rwxr-xr-x    1 root     root       10.9K Jul  6 04:09 /etc/init.d/unblockneteasemusic

/usr/share/unblockneteasemusic:
drwxr-xr-x    2 root     root        3.4K Jul 25 07:21 core
-rw-r--r--    1 root     root          41 Jul 25 03:03 core_local_ver
-rwxr-xr-x    1 root     root        5.5K Jul  6 04:09 debugging.sh
-rwxr-xr-x    1 root     root         348 Jul  6 04:09 log_check.sh
drwxr-xr-x    2 root     root        3.4K Jul 25 07:21 rules
-rwxr-xr-x    1 root     root        2.9K Jul  6 04:09 update.sh
-rw-r--r--    1 root     root           0 Jul 25 03:03 update_core_successfully

config unblockneteasemusic 'config'
	option replace_music_source 'dont_replace'
	option use_custom_cookie '0'
	option local_vip '0'
	option auto_update '1'
	option update_time '3'
	option advanced_mode '0'
	option enable '1'
	option enable_flac '1'
	option music_source 'default'



UnblockNeteaseMusic Node.js info:
Git HEAD version: 7cbc0acff167f78748f69709894dd6a0747ccdbc
Core version: 0.27.0-rc.6
-rw-r--r--    1 root     root      282.4K Jul 25 03:02 app.js
-rw-r--r--    1 root     root          85 Jul 25 03:02 app.js.LICENSE.txt
-rw-r--r--    1 root     root       30.0K Jul 25 03:02 bridge.js
-rw-r--r--    1 root     root          85 Jul 25 03:03 bridge.js.LICENSE.txt
-rw-r--r--    1 root     root         790 Jul 25 03:03 ca.crt
-rw-r--r--    1 root     root         843 Jul 25 03:03 server.crt
-rw-r--r--    1 root     root         359 Jul 25 03:03 server.key


Netease networking info:
< Location: http://m10.music.126.net/20220727100310/59aafe928af50be1c27c11e41f8db975/ymusic/obj/w5zDlMODwrDDiGjCn8Ky/3057940231/3d32/93a3/4db1/0757f3a378b41e09ca2767c1abd47afa.mp3
{"code":200,"data":{"music.163.com":{"ip":["115.236.118.34","115.236.121.4","59.111.19.33","59.111.160.195","193.112.159.225","39.105.175.128","47.100.127.239","182.92.170.253","39.105.63.80","118.24.63.156"],"ipv4ScoreDelay":0,"prefer":"ipv4","score":false,"ttl":600}}}

Port status:
tcp        0      0 0.0.0.0:5200            0.0.0.0:*               LISTEN      21486/node
tcp        0      0 0.0.0.0:5201            0.0.0.0:*               LISTEN      21486/node


PROCD running info:
{
	"unblockneteasemusic": {
		"instances": {
			"unblockneteasemusic": {
				"running": true,
				"pid": 21486,
				"command": [
					"node",
					"/usr/share/unblockneteasemusic/core/app.js",
					"-a",
					"0.0.0.0",
					"-p",
					"5200:5201",
					"-e",
					"https://music.163.com"
				],
				"term_timeout": 5,
				"env": {
					"ENABLE_FLAC": "true",
					"JSON_LOG": "true",
					"LOG_FILE": "/tmp/unblockneteasemusic.log",
					"SIGN_CERT": "/usr/share/unblockneteasemusic/core/server.crt",
					"SIGN_KEY": "/usr/share/unblockneteasemusic/core/server.key"
				},
				"respawn": {
					"threshold": 3600,
					"timeout": 5,
					"retry": 5
				}
			}
		},
		"triggers": [
			[
				"config.change",
				[
					"if",
					[
						"eq",
						"package",
						"unblockneteasemusic"
					],
					[
						"run_script",
						"/etc/init.d/unblockneteasemusic",
						"reload"
					]
				],
				1000
			]
		]
	}
}


Firewall info:
Chain netease_cloud_music (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             0.0.0.0/8           
RETURN     all  --  anywhere             10.0.0.0/8          
RETURN     all  --  anywhere             127.0.0.0/8         
RETURN     all  --  anywhere             169.254.0.0/16      
RETURN     all  --  anywhere             172.16.0.0/12       
RETURN     all  --  anywhere             192.168.0.0/16      
RETURN     all  --  anywhere             base-address.mcast.net/4 
RETURN     all  --  anywhere             240.0.0.0/4         
REDIRECT   tcp  --  anywhere             anywhere             ! match-set acl_neteasemusic_http src tcp dpt:www redir ports 5200
REDIRECT   tcp  --  anywhere             anywhere             ! match-set acl_neteasemusic_https src tcp dpt:https redir ports 5201

Name: neteasemusic
Type: hash:ip
Revision: 4
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 1064
References: 1
Number of entries: 18
Members:
223.252.199.66
115.236.121.4
193.112.159.225
59.111.181.38
59.111.160.195
39.105.63.80
115.236.118.34
39.105.175.128
47.100.127.239
115.236.121.1
118.24.63.156
59.111.19.33
115.236.118.33
59.111.181.60
59.111.181.35
223.252.199.67
59.111.160.197
182.92.170.253

Name: acl_neteasemusic_http
Type: hash:ip
Revision: 4
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 200
References: 1
Number of entries: 0
Members:

Name: acl_neteasemusic_https
Type: hash:ip
Revision: 4
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 200
References: 1
Number of entries: 0
Members:

dhcp-option=252,http://192.168.8.1:5200/proxy.pac
ipset=/.music.163.com/neteasemusic
ipset=/interface.music.163.com/neteasemusic
ipset=/interface3.music.163.com/neteasemusic
ipset=/apm.music.163.com/neteasemusic
ipset=/apm3.music.163.com/neteasemusic
ipset=/clientlog.music.163.com/neteasemusic
ipset=/clientlog3.music.163.com/neteasemusic


Testing source replacing...
{"data":[{"id":33190502,"url":null,"br":0,"size":0,"md5":null,"code":404,"expi":1200,"type":null,"gain":0.0,"fee":0,"uf":null,"payed":0,"flag":257,"canExtend":false,"freeTrialInfo":null,"level":null,"encodeType":null,"freeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"listenType":null},"freeTimeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"type":0,"remainTime":0},"urlSource":0,"rightSource":0}],"code":200}
{"data":[{"id":33190502,"url":"https://music.163.com/package/aHR0cDovL3Vwb3Mtc3otbWlycm9yY29zLmJpbGl2aWRlby5jb20vdWdheGNvZGUvbTE5MDgwNndzMjZnMTdnMnNjZHR3azIyYjk3c2FrMDAtMTkyay5tNGE_ZT1pZzhldXhaTTJyTmNOYmRsaG9Odk5DOEJxSkl6TmJmcVhCdkVxeFRFdG84QlRyTnZOMEd2VDkwVzVKWk1rWF9ZTjBNdlhnOGdORVY0TkM4eE5FVjROMDNlTjBCNXRabHFOeFRFdG84QlRyTnZOZVpWdUoxMEtqX2cyVUIwMkowbU4wQjV0WmxxTkNORXRvOEJUck52TkM3TVRYNTAyQzhmMmptTVFKNm1xRjJma2ExbXF4NmdxajBlTjBCNTk5TT0mdWlwaz01Jm5icz0xJmRlYWRsaW5lPTE2NTg4OTMwOTAmZ2VuPXBsYXl1cmx2MiZvcz1jb3NidiZvaT0zMDc5MDQwMDYyJnRyaWQ9ZTY5OGUwNDJhOWMxNDNjM2IwYTEzNjYyN2Q1ZWJjOTlCJm1pZD0wJnBsYXRmb3JtPXBjJnVwc2lnPTgxMzM3YWZlMmVkNTIwMTZjMjJlNWYyNjAwOGM2OGE4JnVwYXJhbXM9ZSx1aXBrLG5icyxkZWFkbGluZSxnZW4sb3Msb2ksdHJpZCxtaWQscGxhdGZvcm0mYnZjPXZvZCZuZXR0eXBlPTAmb3JkZXJpZD0wLDEmbG9nbz0wMDAwMDAwMA==/33190502.mp3","br":128000,"size":6351104,"md5":"200f8d9f04f6abc789ea80192b9938f4","code":200,"expi":1200,"type":"mp3","gain":0,"fee":0,"uf":null,"payed":0,"flag":0,"canExtend":false,"freeTrialInfo":null,"level":null,"encodeType":null,"freeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"listenType":null},"freeTimeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"type":0,"remainTime":0},"urlSource":0,"rightSource":0}],"code":200}
{"level":50,"time":1658885890527,"pid":21486,"hostname":"OpenWrt","scope":"provider/yt-dlp","name":"YtDlpNotInstalled","stack":"YtDlpNotInstalled: You must install \"yt-dlp\" before using the \"ytdlp\" source.\n    at getUrl (/usr/share/unblockneteasemusic/core/app.js:250:81)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async /usr/share/unblockneteasemusic/core/app.js:253:72\n    at async CacheStorage.cache (/usr/share/unblockneteasemusic/core/app.js:13:22)\n    at async getAudioFromSource (/usr/share/unblockneteasemusic/core/app.js:187:17)","type":"Error","msg":"You must install \"yt-dlp\" before using the \"ytdlp\" source."}
{"level":50,"time":1658885890529,"pid":21486,"hostname":"OpenWrt","scope":"provider/match","name":"YtDlpNotInstalled","stack":"YtDlpNotInstalled: You must install \"yt-dlp\" before using the \"ytdlp\" source.\n    at getUrl (/usr/share/unblockneteasemusic/core/app.js:250:81)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async /usr/share/unblockneteasemusic/core/app.js:253:72\n    at async CacheStorage.cache (/usr/share/unblockneteasemusic/core/app.js:13:22)\n    at async getAudioFromSource (/usr/share/unblockneteasemusic/core/app.js:187:17)","type":"Error","msg":"You must install \"yt-dlp\" before using the \"ytdlp\" source."}
{"level":30,"time":1658885891361,"pid":21486,"hostname":"OpenWrt","scope":"provider/match","audioId":33190502,"songName":"å›ã®ã¾ã¾ã§","url":"http://upos-sz-mirrorcos.bilivideo.com/ugaxcode/m190806ws26g17g2scdtwk22b97sak00-192k.m4a?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1658893090&gen=playurlv2&os=cosbv&oi=3079040062&trid=e698e042a9c143c3b0a136627d5ebc99B&mid=0&platform=pc&upsig=81337afe2ed52016c22e5f26008c68a8&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=0,1&logo=00000000","msg":"Replaced: [33190502] 君のままで"}


Log is available at:
https://litter.catbox.moe/3myjrs.txt
https://transfer.sh/Vwv6Yf/unm-debugging-output.txt

```

**Comment by suyu0925** [comment]
![version](https://user-images.githubusercontent.com/7429906/181143213-45def356-9a41-433e-8735-40f40819b8df.png)
windows客户端版本是截止至目前的最新版2.10.2(Build:200154)(Patch:1:1c73aaa)

**Comment by 1715173329** [comment]
- UnblockNeteaseMusic/server#780

**Comment by a393310872** [comment]
用2.9.10就行了.不要用最新.
