### ISSUE TITLE
开启后歌曲高亮但无法播放

### ISSUE THREAD

**Issue by Zaphkito** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#177]
问问，为什么我插件开启以后歌曲高亮了，但是无法播放
此时没有开启任何代理软件
![image](https://user-images.githubusercontent.com/64299266/182454839-41b55e03-cbc9-4c08-b683-99f680bfa0ae.png)

**Comment by Zaphkito** [comment]
网页端也无法播放，会报出如下错误
INFO: (app) HTTP Server running @ http://0.0.0.0:5200
INFO: (app) HTTPS Server running @ http://0.0.0.0:5201
ERROR: (provider/match) Unexpected end of JSON input
    SyntaxError: Unexpected end of JSON input
        at JSON.parse (<anonymous>)
        at /usr/share/unblockneteasemusic/core/app.js:275:408
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async CacheStorage.cache (/usr/share/unblockneteasemusic/core/app.js:13:22)
        at async getAudioFromSource (/usr/share/unblockneteasemusic/core/app.js:187:17)
        at async Promise.any (index 0)
        at async module.exports (/usr/share/unblockneteasemusic/core/app.js:207:234)
        at async Promise.all (index 0)
ERROR: (hook) All promises were rejected
    AggregateError: All promises were rejected
ERROR: (hook) All promises were rejected
    AggregateError: All promises were rejected

**Comment by Zaphkito** [comment]
![image](https://user-images.githubusercontent.com/64299266/182457234-95dc48aa-8e7d-441f-abb0-909089cb028e.png)
草，旧版本可以正常播放

**Comment by 1715173329** [comment]
请注意，仅支持网易云音乐 2.9.10 或更低版本。

**Comment by 1715173329** [comment]
#695 网页端客户端的 api 应该一并变动，因此导致无法使用。
