### ISSUE TITLE
QQ音乐填入个人cookie后无法正常解析

### ISSUE THREAD

**Issue by uzuki5245** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#178]
使用默认设置时可以正常使用，但是填入个人cookie后一直播放失败。
编程小白，查了一个多小时的资料，都没能搞明白要怎么处理...

INFO: (app) HTTP Server running @ http://0.0.0.0:5200
INFO: (app) HTTPS Server running @ http://0.0.0.0:5201
ERROR: (provider/match) Unexpected end of JSON input
    SyntaxError: Unexpected end of JSON input
        at JSON.parse (<anonymous>)
        at /usr/share/unblockneteasemusic/core/app.js:294:408
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
        at async CacheStorage.cache (/usr/share/unblockneteasemusic/core/app.js:13:22)
        at async getAudioFromSource (/usr/share/unblockneteasemusic/core/app.js:201:17)
ERROR: (hook) No one promise resolved
    Error
        at /usr/share/unblockneteasemusic/core/app.js:1371:249
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
ERROR: (provider/match) Unexpected end of JSON input
    SyntaxError: Unexpected end of JSON input
        at JSON.parse (<anonymous>)
        at /usr/share/unblockneteasemusic/core/app.js:294:408
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
        at async CacheStorage.cache (/usr/share/unblockneteasemusic/core/app.js:13:22)
        at async getAudioFromSource (/usr/share/unblockneteasemusic/core/app.js:201:17)
ERROR: (hook) No one promise resolved
    Error
        at /usr/share/unblockneteasemusic/core/app.js:1371:249
        at processTicksAndRejections (internal/process/task_queues.js:95:5)

[Powered by LuCI Master (git-22.211.60098-feaa27a)](https://github.com/coolsnowwolf/luci) / OpenWrt R22.4.1

**Comment by 1715173329** [comment]
UnblockNeteaseMusic/server#788 it needs rework
