### ISSUE TITLE
mac 解锁错误，日志如下

### ISSUE THREAD

**Issue by guider** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#184]
ERROR: (hook) A error occurred in hook.request.after when hooking https://music.163.com/eapi/batch.
    Error: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length
        at Decipheriv.final (internal/crypto/cipher.js:174:29)
        at decrypt (/usr/share/unblockneteasemusic/core/app.js:50:56)
        at Object.decrypt (/usr/share/unblockneteasemusic/core/app.js:52:90)
        at /usr/share/unblockneteasemusic/core/app.js:98:163
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
    library: digital envelope routines
    function: EVP_DecryptFinal_ex
    reason: wrong final block length
    code: ERR_OSSL_EVP_WRONG_FINAL_BLOCK_LENGTH

**Comment by byl0561** [comment]
I have the same issue on windows

OS: Windows 11 22000.856
netease music: 2.10.3 build200198
openwrt:  19.07.4

err log:
{"level":50,"time":1660968129220,"pid":21312,"hostname":"OpenWrt","scope":"hook","library":"digital envelope routines","function":"EVP_DecryptFinal_ex","reason":"wrong final block length","code":"ERR_OSSL_EVP_WRONG_FINAL_BLOCK_LENGTH","stack":"Error: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length\n    at Decipheriv.final (internal/crypto/cipher.js:170:29)\n    at decrypt (/usr/share/unblockneteasemusic/core/app.js:50:56)\n    at Object.decrypt (/usr/share/unblockneteasemusic/core/app.js:52:90)\n    at /usr/share/unblockneteasemusic/core/app.js:98:163\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:94:5)","type":"Error","msg":"A error occurred in hook.request.after when hooking https://interface.music.163.com/eapi/song/enhance/player/url/v1."}

**Comment by Kimaru-bili** [comment]
我也一样 复现了这个问题
OS: Windows 11 22000.856
netease music: 2.10.3 build200211
openwrt: R22.7.7
INFO: (app) HTTP Server running @ http://0.0.0.0:5200
INFO: (app) HTTPS Server running @ http://0.0.0.0:5201
ERROR: (hook) A error occurred in hook.request.after when hooking https://interface.music.163.com/eapi/song/enhance/player/url/v1.
    Error: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length
        at Decipheriv.final (node:internal/crypto/cipher:193:29)
        at decrypt (/usr/share/unblockneteasemusic/core/app.js:50:56)
        at Object.decrypt (/usr/share/unblockneteasemusic/core/app.js:52:90)
        at /usr/share/unblockneteasemusic/core/app.js:98:163
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
    library: digital envelope routines
    function: EVP_DecryptFinal_ex
    reason: wrong final block length
    code: ERR_OSSL_EVP_WRONG_FINAL_BLOCK_LENGTH
