### ISSUE TITLE
替换歌曲时候 报错，但是歌曲可以正常听

### ISSUE THREAD

**Issue by 0x-newe** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#234]
### Bug 描述

主要报错内容 
INFO: (provider/match) Replaced: [1403215687] 想见你想见你想见你
    audioId: 1403215687
    songName: "想见你想见你想见你"
    url: "http://sr.sycdn.kuwo.cn/8b2518fabd778372679d04cb7a334bc7/63e8962e/resource/n2/52/80/1387467101.mp3"
ERROR: (provider/match) socket hang up
    Error: socket hang up
        at connResetException (internal/errors.js:639:14)
        at Socket.socketOnEnd (_http_client.js:499:23)
        at Socket.emit (events.js:412:35)
        at endReadableNT (internal/streams/readable.js:1333:12)
        at processTicksAndRejections (internal/process/task_queues.js:82:21)
    code: ECONNRESET
ERROR: (hook) A error occurred in hook.request.after when hooking https://music.163.com/api/batch?.
    Error: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length
        at Decipheriv.final (internal/crypto/cipher.js:174:29)
        at decrypt (/usr/share/unblockneteasemusic/core/app.js:51:56)
        at Object.decrypt (/usr/share/unblockneteasemusic/core/app.js:53:90)
        at /usr/share/unblockneteasemusic/core/app.js:100:163
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
    library: digital envelope routines
    function: EVP_DecryptFinal_ex
    reason: wrong final block length
    code: ERR_OSSL_EVP_WRONG_FINAL_BLOCK_LENGTH
INFO: (provider/match) Replaced: [190499] 给你们
    audioId: 190499
    songName: "给你们"
    url: "http://other.player.rc03.sycdn.kuwo.cn/204b803a16ddeccc10364f0f8d1c9b08/63e89668/resource/s1/46/88/807762197.flac"
ERROR: (provider/match) socket hang up
    Error: socket hang up
        at connResetException (internal/errors.js:639:14)
        at Socket.socketOnEnd (_http_client.js:499:23)
        at Socket.emit (events.js:412:35)
        at endReadableNT (internal/streams/readable.js:1333:12)
        at processTicksAndRejections (internal/process/task_queues.js:82:21)
    code: ECONNRESET

### 预期行为

之前版本是没有报错，希望作者能说明一下 这是由什么原因引起的报错。谢谢

### 调试报告

https://litter.catbox.moe/5zfyu5.txt

### 条款

- [X] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [X] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。
- [X] 我同意作者没有任何义务必须解答我的问题，尤其是缺少恰当的描述和日志。

**Comment by 1715173329** [comment]
https://github.com/UnblockNeteaseMusic/server/issues/972

我也希望有人给我说明是什么情况。

**Comment by 0x-newe** [comment]
> https://github.com/UnblockNeteaseMusic/server/issues/972
> 
> 
> 
> 我也希望有人给我说明是什么情况。

好的  大佬

**Comment by 1715173329** [comment]
已修复
