### ISSUE TITLE
同一op局域网下，本地mac可以解锁，ios不可以解锁（大佬救命）

### ISSUE THREAD

**Issue by zkx8525** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#269]
### Bug 描述

同一op局域网下，本地mac可以解锁，ios不可以解锁，ios已经下载证书并且信任，而且解锁就是很随机，也没有本地会员，而pc端就啥问题也没有

### 调试报告

INFO: (app) HTTP Server running @ http://0.0.0.0:5200
INFO: (app) HTTPS Server running @ http://0.0.0.0:5201
ERROR (YtDlpNotInstalled): (provider/yt-dlp) You must install "yt-dlp" before using the "ytdlp" source.
    YtDlpNotInstalled: You must install "yt-dlp" before using the "ytdlp" source.
        at p (/usr/share/unblockneteasemusic/core/app.js:3:38956)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async d (/usr/share/unblockneteasemusic/core/app.js:3:38997)
        at async u.cache (/usr/share/unblockneteasemusic/core/app.js:2:1243)
        at async m (/usr/share/unblockneteasemusic/core/app.js:3:28729)
        at async Promise.allSettled (index 4)
        at async b (/usr/share/unblockneteasemusic/core/app.js:3:29099)
        at async Promise.all (index 0)
ERROR (YtDlpNotInstalled): (provider/match) You must install "yt-dlp" before using the "ytdlp" source.
    YtDlpNotInstalled: You must install "yt-dlp" before using the "ytdlp" source.
        at p (/usr/share/unblockneteasemusic/core/app.js:3:38956)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async d (/usr/share/unblockneteasemusic/core/app.js:3:38997)
        at async u.cache (/usr/share/unblockneteasemusic/core/app.js:2:1243)
        at async m (/usr/share/unblockneteasemusic/core/app.js:3:28729)
        at async Promise.allSettled (index 4)
        at async b (/usr/share/unblockneteasemusic/core/app.js:3:29099)
        at async Promise.all (index 0)
INFO: (provider/match) Replaced: [1962165890] Intro
    audioId: 1962165890
    songName: "Intro"
    url: "http://lv.sycdn.kuwo.cn/73a44ecce61ae33c32751ec754ced677/64930692/resource/30106/trackmedia/F000001vOi9R3roiHq.flac?bitrate"

### 条款

- [X] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [X] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by bauw2008** [comment]
app.js.这是内核错误吧，换个音源应该可以解决。

**Comment by 1715173329** [comment]
没有调试报告。iOS 问题已在新的版本中优化。
