### ISSUE TITLE
其他功能正常，下载音乐失败

### ISSUE THREAD

**Issue by zkx8525** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#271]
### Bug 描述

日志文件：
ERROR: (hook) A error occurred in hook.request.after when hooking http://music.163.com/eapi/song/enhance/player/url.
    SyntaxError: Unexpected token { in JSON at position 25
        at parse (<anonymous>)
        at JSON.parse (/usr/share/unblockneteasemusic/core/app.js:81:120113)
        at /usr/share/unblockneteasemusic/core/app.js:3:10157
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### 调试报告

ERROR: (hook) A error occurred in hook.request.after when hooking http://music.163.com/eapi/song/enhance/player/url.
    SyntaxError: Unexpected token { in JSON at position 25
        at parse (<anonymous>)
        at JSON.parse (/usr/share/unblockneteasemusic/core/app.js:81:120113)
        at /usr/share/unblockneteasemusic/core/app.js:3:10157
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### 条款

- [X] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [X] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by 1715173329** [comment]
- 没有调试报告
- 你的问题应该去主库那边提
