### ISSUE TITLE
This song "?" is not available in any source

### ISSUE THREAD

**Issue by empty-233** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#283]
### Bug 描述

使用 `pyncmd` 解锁时有概率遇到

### 复现步骤

使用 `pyncmd` 解锁

### 调试报告

INFO: (app) HTTP Server running @ http://0.0.0.0:5200
INFO: (app) HTTPS Server running @ http://0.0.0.0:5201
ERROR: (provider/match) Unexpected token < in JSON at position 0
    SyntaxError: Unexpected token < in JSON at position 0
        at parse (<anonymous>)
        at JSON.parse (/usr/share/unblockneteasemusic/core/app.js:81:121015)
        at /usr/share/unblockneteasemusic/core/app.js:3:43249
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async u.cache (/usr/share/unblockneteasemusic/core/app.js:2:1244)
        at async m (/usr/share/unblockneteasemusic/core/app.js:3:29282)
ERROR (SongNotAvailable): (hook) This song "?" is not available in any source
    SongNotAvailable: This song "?" is not available in any source
        at b (/usr/share/unblockneteasemusic/core/app.js:3:29823)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async Promise.all (index 0)
ERROR: (provider/match) Unexpected token < in JSON at position 0
    SyntaxError: Unexpected token < in JSON at position 0
        at parse (<anonymous>)
        at JSON.parse (/usr/share/unblockneteasemusic/core/app.js:81:121015)
        at /usr/share/unblockneteasemusic/core/app.js:3:43249
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async u.cache (/usr/share/unblockneteasemusic/core/app.js:2:1244)
        at async m (/usr/share/unblockneteasemusic/core/app.js:3:29282)
ERROR (SongNotAvailable): (hook) This song "?" is not available in any source
    SongNotAvailable: This song "?" is not available in any source
        at b (/usr/share/unblockneteasemusic/core/app.js:3:29823)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async Promise.all (index 0)

### 其他信息

核心版本号：10d0898

固件版本：OpenWrt R23.6.6 / LuCI Master (git-23.242.63652-d82d969)
固件是基于lede编译的

客户端版本：Windows uwp 1.4.1.0

### 条款

- [X] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [X] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by 1715173329** [comment]
没有调试报告。网络到网易云音乐服务器有问题，但实际上此错误无所谓。
