### ISSUE TITLE
插件显示运行中 但实际不起作用

### ISSUE THREAD

**Issue by DavideSOGG** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#316]
### Bug 描述

插件显示运行中 但实际不起作用 无法解锁音乐 看起来似乎是部分配置失败了。
核心最新版成功安装 
各平台证书已安装
运行时的日志显示信息为：
INFO: (app) HTTP Server running @ http://:::5200
INFO: (app) HTTPS Server running @ http://:::5201
ERROR: (hook) All promises were rejected
    AggregateError: All promises were rejected

P.S.高级设置中尝试过 “不使用劫持”以及“使用IPset劫持”
指定过网易云音乐IP 其余设置默认

### 调试报告

Launching luci-app-unblockneteasmusic Debugging Tool...

OpenWrt info:
{
	"kernel": "5.10.221",
	"hostname": "iStoreOS",
	"system": "ARMv8 Processor rev 0",
	"model": "FriendlyElec NanoPi R5S",
	"board_name": "friendlyelec,nanopi-r5s",
	"rootfs_type": "squashfs",
	"release": {
		"distribution": "iStoreOS",
		"version": "22.03.7",
		"revision": "2024080210",
		"target": "rockchip/rk35xx",
		"description": "iStoreOS 22.03.7 2024080210"
	}
}

uclient-fetch info:
Package: uclient-fetch
Version: 2023-04-13-007d9454-1
Depends: libc, libuclient20201210
Provides: wget
Status: install user installed
Section: net
Architecture: aarch64_cortex-a53
Size: 8229
Filename: uclient-fetch_2023-04-13-007d9454-1_aarch64_cortex-a53.ipk
Description: Tiny wget replacement using libuclient
Installed-Time: 1721975007

Package: libustream-wolfssl20201210
Version: 2022-12-08-9217ab46-2
Depends: libc, libubox20220515, libwolfssl5.7.2.ee39414e
Provides: libustream-wolfssl
Conflicts: libustream-openssl
Status: unknown ok not-installed
Section: libs
Architecture: aarch64_cortex-a53
Size: 5190
Filename: libustream-wolfssl20201210_2022-12-08-9217ab46-2_aarch64_cortex-a53.ipk
Description: ustream SSL Library (wolfssl)

Package: libustream-openssl20201210
Version: 2022-12-08-9217ab46-2
Depends: libc, libubox20220515, libopenssl1.1
Provides: libustream-openssl
Status: install user installed
Section: libs
Architecture: aarch64_cortex-a53
Size: 5677
Filename: libustream-openssl20201210_2022-12-08-9217ab46-2_aarch64_cortex-a53.ipk
Description: ustream SSL Library (openssl)
Installed-Time: 1721975007

Package: libustream-mbedtls20201210
Version: 2022-12-08-9217ab46-2
Depends: libc, libubox20220515, libmbedtls12
Provides: libustream-mbedtls
Conflicts: libustream-openssl, libustream-wolfssl
Status: unknown ok not-installed
Section: libs
Architecture: aarch64_cortex-a53
Size: 5492
Filename: libustream-mbedtls20201210_2022-12-08-9217ab46-2_aarch64_cortex-a53.ipk
Description: ustream SSL Library (mbedtls)

Package: wget-ssl
Version: 1.21.4-1
Depends: libc, libpcre2, zlib, libopenssl1.1, librt
Provides: gnu-wget, wget
Status: unknown ok not-installed
Section: net
Architecture: aarch64_cortex-a53
Size: 217211
Filename: wget-ssl_1.21.4-1_aarch64_cortex-a53.ipk
Description: Wget is a network utility to retrieve files from the Web using http and ftp, the two most widely used Internet protocols. It works non-interactively, so it will work in the background, after having logged off. The program supports recursive retrieval of web-authoring pages as well as ftp sites -- you can use wget to make mirrors of archives and home pages or to travel the Web like a WWW robot. This package is built with SSL support.

Package: wget-ssl
Version: 1.21.4-2
Depends: libc, libpcre2, zlib, libopenssl1.1, librt
Provides: gnu-wget, wget
Status: install user installed
Architecture: aarch64_cortex-a53
Installed-Time: 1721975007

--2024-11-24 23:35:20--  https://api.github.com/repos/UnblockNeteaseMusic/server/commits?sha=enhanced&path=precompiled
Resolving api.github.com... 20.205.243.168
Connecting to api.github.com|20.205.243.168|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/json]
Saving to: 'STDOUT'

     0K .......... .......... .......... .......... ..........  105K
    50K .......... .......... .......... .......... ..........  321K
   100K .......... .......... .......... ......                11.5M=0.6s

2024-11-24 23:35:22 (214 KB/s) - written to stdout [139821]

d99ad1e6fe17a8f421ccf4876b04ca4c7d4083e8

Node.js info:
Package: node
Version: v16.20.2-1
Depends: libc, libstdcpp6, libopenssl1.1, zlib, libnghttp2-14, libuv1, libcares, libatomic1
Status: install ok installed
Section: lang
Architecture: aarch64_cortex-a53
Size: 11542753
Filename: node_v16.20.2-1_aarch64_cortex-a53.ipk
Description: Node.js® is a JavaScript runtime built on Chrome's V8 JavaScript engine. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient. Node.js' package ecosystem, npm, is the largest ecosystem of open source libraries in the world. *** The following preparations must be made on the host side. *** 1. gcc 8.3 or higher is required. 2. To build a 32-bit target, gcc-multilib, g++-multilib are required. 3. Requires libatomic package. (If necessary, install the 32-bit library at the same time.) ex) sudo apt-get install gcc-multilib g++-multilib
Installed-Time: 1732455920

Node.js is placed at /usr/bin/node
Node.js version: v16.20.2

luci-app-unblockneteasmusic info:
Package: luci-app-unblockneteasemusic
Version: 3.2
Depends: libc, dnsmasq-full, node
Status: install user installed
Architecture: all
Conffiles:
 /etc/config/unblockneteasemusic 0100db4c709a797fdb03ce6b172c860b860f6bea0e0614477d9dda9b1b574b94
Installed-Time: 1732455920

-rw-r--r--    1 root     root         159 Nov 24 23:32 /etc/config/unblockneteasemusic
-rwxr-xr-x    1 root     root       10.9K Jan  1  2024 /etc/init.d/unblockneteasemusic

/usr/share/unblockneteasemusic:
drwx------    2 root     root        4.0K Nov 24 23:31 core
-rw-------    1 root     root          41 Nov 24 23:31 core_local_ver
-rwxr-xr-x    1 root     root        5.3K Jan  1  2024 debugging.sh
-rwxr-xr-x    1 root     root         392 Jan  1  2024 log_check.sh
-rw-r--r--    1 root     root        1.6K Jan  1  2024 nftables.ut
-rwxr-xr-x    1 root     root        3.0K Jan  1  2024 update.sh

config unblockneteasemusic 'config'
	option disable_upgrade_check '1'
	option enable '1'
	option enable_flac '1'
	option replace_music_source 'dont_replace'

UnblockNeteaseMusic Node.js info:
Git HEAD version: d99ad1e6fe17a8f421ccf4876b04ca4c7d4083e8
Core version: 0.27.8-patch.1
-rw-------    1 root     root      219.3K Nov 24 23:31 app.js
-rw-------    1 root     root      184.0K Nov 24 23:31 bridge.js
-rw-------    1 root     root         790 Nov 24 23:31 ca.crt
-rw-------    1 root     root         932 Nov 24 23:31 server.crt
-rw-------    1 root     root         359 Nov 24 23:31 server.key

Netease networking info:
< Location: http://m10.music.126.net/20241125000024/21af4557890ab52377b2eb714275ff9f/ymusic/obj/w5zDlMODwrDDiGjCn8Ky/3057940231/3d32/93a3/4db1/0757f3a378b41e09ca2767c1abd47afa.mp3
{"code":200,"data":{"music.163.com":{"ip":["111.124.200.65","1.95.21.33","47.100.127.239","182.92.170.253","193.112.159.225","39.105.175.128","39.105.63.80","118.24.63.156"],"ipv4ScoreDelay":0,"prefer":"ipv4","score":false,"ttl":600}}}

Port status:
tcp        0      0 :::5200                 :::*                    LISTEN      1821/node
tcp        0      0 :::5201                 :::*                    LISTEN      1821/node

PROCD running info:
{
	"unblockneteasemusic": {
		"instances": {
			"log-check": {
				"running": true,
				"pid": 1822,
				"command": [
					"/usr/share/unblockneteasemusic/log_check.sh"
				],
				"term_timeout": 5,
				"respawn": {
					"threshold": 3600,
					"timeout": 5,
					"retry": 5
				}
			},
			"unblockneteasemusic": {
				"running": true,
				"pid": 1821,
				"command": [
					"node",
					"/usr/share/unblockneteasemusic/core/app.js",
					"-a",
					"::",
					"-p",
					"5200:5201",
					"-o",
					"kugou",
					"-e",
					"https://music.163.com"
				],
				"term_timeout": 5,
				"env": {
					"DISABLE_UPGRADE_CHECK": "true",
					"ENABLE_FLAC": "true",
					"LOG_FILE": "/var/run/unblockneteasemusic/run.log",
					"LOG_LEVEL": "info",
					"SIGN_CERT": "/usr/share/unblockneteasemusic/core/server.crt",
					"SIGN_KEY": "/usr/share/unblockneteasemusic/core/server.key"
				},
				"respawn": {
					"threshold": 3600,
					"timeout": 5,
					"retry": 5
				}
			}
		},
		"triggers": [
			[
				"config.change",
				[
					"if",
					[
						"eq",
						"package",
						"unblockneteasemusic"
					],
					[
						"run_script",
						"/etc/init.d/unblockneteasemusic",
						"reload"
					]
				],
				1000
			]
		]
	}
}

Firewall info:
Chain netease_cloud_music (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             0.0.0.0/8           
RETURN     all  --  anywhere             10.0.0.0/8          
RETURN     all  --  anywhere             127.0.0.0/8         
RETURN     all  --  anywhere             169.254.0.0/16      
RETURN     all  --  anywhere             172.16.0.0/12       
RETURN     all  --  anywhere             192.168.0.0/16      
RETURN     all  --  anywhere             base-address.mcast.net/4 
RETURN     all  --  anywhere             240.0.0.0/4         
REDIRECT   tcp  --  anywhere             anywhere             ! match-set acl_neteasemusic_http src tcp dpt:www redir ports 5200
REDIRECT   tcp  --  anywhere             anywhere             ! match-set acl_neteasemusic_https src tcp dpt:https redir ports 5201

Name: neteasemusic
Type: hash:ip
Revision: 4
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 1032
References: 1
Number of entries: 17
Members:
59.111.19.33
39.105.63.80
49.67.73.77
47.100.127.239
182.92.170.253
1.95.21.33
111.124.200.67
59.111.160.195
183.136.182.18
111.124.200.65
118.24.63.156
111.124.200.68
39.105.175.128
193.112.159.225
1.95.21.34
115.238.119.67
1.95.21.35

Name: acl_neteasemusic_http
Type: hash:mac
Revision: 0
Header: hashsize 1024 maxelem 65536
Size in memory: 208
References: 1
Number of entries: 0
Members:

Name: acl_neteasemusic_https
Type: hash:mac
Revision: 0
Header: hashsize 1024 maxelem 65536
Size in memory: 208
References: 1
Number of entries: 0
Members:

dhcp-option=252,http://192.168.2.100:5200/proxy.pac
ipset=/.music.163.com/neteasemusic
ipset=/interface.music.163.com/neteasemusic
ipset=/interface3.music.163.com/neteasemusic
ipset=/apm.music.163.com/neteasemusic
ipset=/apm3.music.163.com/neteasemusic
ipset=/clientlog.music.163.com/neteasemusic
ipset=/clientlog3.music.163.com/neteasemusic

Testing source replacing...
{"data":[{"id":33190502,"url":null,"br":0,"size":0,"md5":null,"code":-110,"expi":1200,"type":null,"gain":0.0,"peak":null,"closedGain":0.0,"closedPeak":0.0,"fee":1,"uf":null,"payed":0,"flag":524292,"canExtend":false,"freeTrialInfo":null,"level":null,"encodeType":null,"channelLayout":null,"freeTrialPrivilege":{"resConsumable":true,"userConsumable":false,"listenType":null,"cannotListenReason":null,"playReason":null,"freeLimitTagType":null},"freeTimeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"type":0,"remainTime":0},"urlSource":0,"rightSource":0,"podcastCtrp":null,"effectTypes":null,"time":0,"message":null,"levelConfuse":null,"musicId":null}],"code":200}
{"data":[{"id":33190502,"url":null,"br":0,"size":0,"md5":null,"code":-110,"expi":1200,"type":null,"gain":0,"peak":null,"closedGain":0,"closedPeak":0,"fee":0,"uf":null,"payed":1,"flag":0,"canExtend":false,"freeTrialInfo":null,"level":null,"encodeType":null,"channelLayout":null,"freeTrialPrivilege":{"resConsumable":true,"userConsumable":false,"listenType":null,"cannotListenReason":null,"playReason":null,"freeLimitTagType":null},"freeTimeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"type":0,"remainTime":0},"urlSource":0,"rightSource":0,"podcastCtrp":null,"effectTypes":null,"time":0,"message":null,"levelConfuse":null,"musicId":null}],"code":200}
INFO: (app) HTTP Server running @ http://:::5200
INFO: (app) HTTPS Server running @ http://:::5201
ERROR: (hook) All promises were rejected
    AggregateError: All promises were rejected

### 条款

- [X] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [X] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by Nigel-NI** [comment]
我遇到了同样的问题。ImmortalWrt，插件版本3.3，核心版本d99ad1e，NFTset劫持方式对局域网设备无效。windows版指定http代理地址为路由器后可以正常使用。
日志在：https://litter.catbox.moe/tj6qzx.txt

**Comment by tcscat** [comment]
我也是

**Comment by gyyst** [comment]
> 我遇到了同样的问题。ImmortalWrt，插件版本3.3，核心版本d99ad1e，NFTset劫持方式对局域网设备无效。windows版指定http代理地址为路由器后可以正常使用。 日志在：https://litter.catbox.moe/tj6qzx.txt
请问我指定windows版代理指向路由器后提示网易云提示网络异常如何解决

**Comment by zxa3256855565** [comment]
+1  我也不起作用

**Comment by zxa3256855565** [comment]
> 我遇到了同样的问题。ImmortalWrt，插件版本3.3，核心版本d99ad1e，NFTset劫持方式对局域网设备无效。windows版指定http代理地址为路由器后可以正常使用。 日志在：https://litter.catbox.moe/tj6qzx.txt

你是正确的，修改为路由器后正常使用，暂时未知原因，我纯小白

**Comment by SqiChiu** [comment]
我也是，用不了，http代理改成路由器后是可以播放音乐，但是个性推荐什么的 全部都显示网络不给力，请检查网络设置

**Comment by 1715173329** [comment]
ipt 下不支持 ipv6，必须关闭对应 v6 解析。
新版客户端兼容问题最新核心已修复。

**Comment by mrxxx66** [comment]
> ipt 下不支持 ipv6，必须关闭对应 v6 解析。 新版客户端兼容问题最新核心已修复。

关了ipv6,我的插件也是能运行，但是不起作用，需要手动配置代理，才生效。
客户端配置代理能正常听，但是插件有报错。
pgc=1"
WARN: (request) The request timed out, or the requester didn't handle the response.
    url: "https://m.music.migu.cn/v5"
ERROR: (provider/match) Unexpected token '<', "<!doctype "... is not valid JSON
    SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON
        at parse (<anonymous>)
        at JSON.parse (/usr/share/unblockneteasemusic/core/app.js:107:9691)
        at /usr/share/unblockneteasemusic/core/app.js:10:13108
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async c.cache (/usr/share/unblockneteasemusic/core/app.js:37:23751)
        at async y (/usr/share/unblockneteasemusic/core/app.js:10:19600)
        at async Promise.any (index 0)
        at async e (/usr/share/unblockneteasemusic/core/app.js:10:22035)
        at async Promise.all (index 0)
